// Turns rendered slide PNGs into an MP4 slideshow with music, using ffmpeg only.
// Usage: node slideshow.mjs slides-dir out.mp4 [--per 3] [--music track.mp3 | --music calm|bright|none]
// A music file is the user's own track. "calm" and "bright" are soft chord pads generated by ffmpeg, free to use anywhere.
import { readdirSync, existsSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join, resolve } from 'node:path';
import { args } from './browser.mjs';

const a = args(process.argv.slice(2), { per: '3', music: 'calm' });
const [dir, out] = a._;
if (!dir || !out) { console.error('Usage: node slideshow.mjs slides-dir out.mp4 [--per 3] [--music file|calm|bright|none]'); process.exit(1); }
const pngs = readdirSync(dir).filter(f => /^slide-\d+\.png$/.test(f)).sort();
if (!pngs.length) { console.error(`No slide-NN.png files in ${dir}; run render-slides.mjs first.`); process.exit(1); }
const per = +a.per, total = per * pngs.length;
mkdirSync(dirname(resolve(out)), { recursive: true });

// Chord frequencies for the generated pads (C major 9 and A minor 7, low and soft).
const PADS = { calm: [130.81, 196.0, 246.94, 293.66], bright: [220.0, 261.63, 329.63, 392.0] };
const inputs = pngs.flatMap(f => ['-loop', '1', '-t', String(per), '-i', join(dir, f)]);
const n = pngs.length;
const video = pngs.map((_, i) => `[${i}:v]scale=1080:-2,setsar=1,fps=30,format=yuv420p,fade=t=in:st=0:d=0.4[v${i}]`).join(';')
  + `;${pngs.map((_, i) => `[v${i}]`).join('')}concat=n=${n}:v=1:a=0[v]`;

let audioIn = [], audio = '', maps = ['-map', '[v]'];
const fadeOut = `afade=t=in:d=1,afade=t=out:st=${Math.max(0, total - 2)}:d=2`;
if (a.music !== 'none' && PADS[a.music]) {
  const tones = PADS[a.music].map(f => `sin(2*PI*${f}*t)`).join('+');
  audioIn = ['-f', 'lavfi', '-i', `aevalsrc='0.06*(${tones})*(0.8+0.2*sin(2*PI*0.25*t))':s=44100:d=${total}`];
  audio = `;[${n}:a]lowpass=f=1200,aecho=0.8:0.7:600:0.3,${fadeOut}[a]`;
  maps.push('-map', '[a]');
} else if (a.music !== 'none') {
  if (!existsSync(a.music)) { console.error(`Music file not found: ${a.music}`); process.exit(1); }
  audioIn = ['-stream_loop', '-1', '-i', a.music];
  audio = `;[${n}:a]atrim=0:${total},${fadeOut}[a]`;
  maps.push('-map', '[a]');
}

execFileSync('ffmpeg', ['-y', '-loglevel', 'error', ...inputs, ...audioIn, '-filter_complex', video + audio, ...maps,
  '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-b:a', '160k', '-t', String(total), '-movflags', '+faststart', resolve(out)]);
console.log(`${out} (${n} slides x ${per}s, music: ${a.music})`);
